
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 08 23:04:09 GMT-04:00 2017
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int APOPPER = 34;
  public static final int CPOPPER = 35;
  public static final int DISPLAY = 2;
  public static final int MULT = 26;
  public static final int LPAREN = 29;
  public static final int INT = 15;
  public static final int MINOR = 28;
  public static final int PRINTLN = 14;
  public static final int MINUS = 25;
  public static final int STATIC = 5;
  public static final int RPAREN = 30;
  public static final int NOT = 20;
  public static final int SEMICOLON = 31;
  public static final int AND = 27;
  public static final int COMMA = 37;
  public static final int CKEY = 33;
  public static final int CLASS = 4;
  public static final int PLUS = 23;
  public static final int MAIN = 7;
  public static final int IF = 10;
  public static final int THIS = 13;
  public static final int NUMBERS = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 21;
  public static final int TRUE = 18;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int AKEY = 32;
  public static final int BECOMES = 24;
  public static final int VOID = 8;
  public static final int ELSE = 12;
  public static final int POINT = 36;
  public static final int WHILE = 11;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 22;
  public static final int STRING = 16;
  public static final int FALSE = 17;
  public static final int LENGTH = 6;
  public static final int IDENTIFIER = 38;
}

