
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 04 20:47:48 GMT-04:00 2017
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 37;
  public static final int LPAREN = 31;
  public static final int INT = 17;
  public static final int MINUS = 25;
  public static final int STATIC = 9;
  public static final int RPAREN = 32;
  public static final int NOT = 30;
  public static final int SEMICOLON = 33;
  public static final int AND = 28;
  public static final int LESSTHAN = 29;
  public static final int CLASS = 6;
  public static final int PLUS = 24;
  public static final int MAIN = 11;
  public static final int IF = 3;
  public static final int THIS = 15;
  public static final int DOT = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 14;
  public static final int RBRACKET = 38;
  public static final int STRING_TYPE = 18;
  public static final int TRUE = 20;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int BECOMES = 27;
  public static final int NUMBER = 40;
  public static final int VOID = 10;
  public static final int TIMES = 26;
  public static final int COLON = 36;
  public static final int LBRACE = 34;
  public static final int ELSE = 4;
  public static final int WHILE = 5;
  public static final int PUBLIC = 8;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 7;
  public static final int STRING = 12;
  public static final int FALSE = 21;
  public static final int PRINT = 13;
  public static final int LENGTH = 23;
  public static final int IDENTIFIER = 39;
}

