/* The following code was generated by JFlex 1.4.3 on 08/05/17 11:04 PM */

/*
 * JFlex specification for the lexical analyzer for a simple demo language.
 * Change this into the scanner for your implementation of MiniJava.
 * CSE 401/P501 Au11
 */


package Scanner;

import java_cup.runtime.*;
import Parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 08/05/17 11:04 PM from the specification file
 * <tt>src/Scanner/minijava.jflex</tt>
 */
public final class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\2\0\1\3\22\0\1\3\1\45\4\0\1\44"+
    "\1\0\1\46\1\47\1\43\1\37\1\51\1\41\1\36\1\5\1\4"+
    "\11\2\1\0\1\50\1\42\1\40\3\0\22\1\1\34\7\1\1\54"+
    "\1\0\1\55\1\0\1\56\1\0\1\14\1\17\1\20\1\7\1\26"+
    "\1\30\1\32\1\31\1\10\2\1\1\13\1\22\1\23\1\25\1\12"+
    "\1\1\1\33\1\11\1\21\1\16\1\24\1\27\1\35\1\15\1\1"+
    "\1\52\1\0\1\53\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\3\1\1\21\2"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\1\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\0\1\24\1\0\2\2\1\25\23\2\1\26\2\24"+
    "\1\2\1\27\3\2\1\26\5\2\1\13\1\30\10\2"+
    "\1\24\6\2\1\31\1\32\1\33\1\34\1\35\13\2"+
    "\1\36\1\2\1\37\1\40\4\2\1\41\1\42\1\43"+
    "\2\2\1\44\1\2\1\45\1\46\1\47\1\50\13\0"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\57\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\u0439\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524\0\136\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\57\0\u08d0\0\u08ff\0\u092e\0\136\0\u095d\0\u098c"+
    "\0\u09bb\0\136\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\136"+
    "\0\136\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\136\0\136\0\136\0\136\0\136\0\u0d96\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\136\0\u0f9b\0\136\0\136\0\u0fca\0\u0ff9\0\u1028\0\u1057"+
    "\0\136\0\136\0\136\0\u1086\0\u10b5\0\136\0\u10e4\0\136"+
    "\0\136\0\136\0\136\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf"+
    "\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\5\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\2\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\3\1\24\1\25\1\26"+
    "\2\3\1\27\1\30\1\3\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\2\60\0\2\3\1\0"+
    "\1\3\2\0\27\3\20\0\1\3\2\0\1\4\1\0"+
    "\1\4\55\0\1\5\2\0\1\5\50\0\5\51\1\52"+
    "\1\53\50\51\1\0\2\3\1\0\1\3\2\0\1\3"+
    "\1\54\25\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\14\3\1\55\4\3\1\56\5\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\12\3\1\57\14\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\7\3"+
    "\1\60\17\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\17\3\1\61\7\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\14\3\1\62\12\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\16\3\1\63\10\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\4\3"+
    "\1\64\22\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\22\3\1\65\1\3\1\66\2\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\5\3\1\67\21\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\16\3"+
    "\1\70\1\71\7\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\16\3\1\72\10\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\4\3\1\73\21\3\1\74"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\22\3"+
    "\1\75\4\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\5\3\1\76\21\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\17\3\1\77\7\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\6\3\1\100\3\3"+
    "\1\101\14\3\20\0\1\3\44\0\1\102\12\0\5\51"+
    "\1\103\1\53\50\51\5\103\1\104\1\53\50\103\6\51"+
    "\1\53\50\51\1\0\2\3\1\0\1\3\2\0\2\3"+
    "\1\105\24\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\12\3\1\106\14\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\5\3\1\107\21\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\10\3\1\110\16\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\14\3"+
    "\1\111\12\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\1\112\26\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\16\3\1\113\10\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\5\3\1\114\21\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\1\3\1\115"+
    "\25\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\7\3\1\116\17\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\1\3\1\117\25\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\12\3\1\120\14\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\20\3\1\121"+
    "\6\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\1\3\1\122\25\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\2\3\1\123\24\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\12\3\1\124\14\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\1\3\1\125"+
    "\25\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\4\3\1\126\22\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\12\3\1\127\14\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\2\3\1\130\24\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\24\3\1\131"+
    "\2\3\20\0\1\3\5\51\1\104\1\53\55\51\1\132"+
    "\1\53\50\51\1\0\2\3\1\0\1\3\2\0\3\3"+
    "\1\133\23\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\12\3\1\134\14\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\4\3\1\135\22\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\23\3\1\136\3\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\4\3"+
    "\1\137\22\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\2\3\1\140\24\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\2\3\1\141\24\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\17\3\1\142\7\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\14\3"+
    "\1\143\12\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\1\144\26\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\17\3\1\145\7\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\17\3\1\146\7\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\4\3\1\147"+
    "\22\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\2\3\1\150\24\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\7\3\1\151\17\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\12\3\1\152\14\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\1\3\1\153"+
    "\25\3\20\0\1\3\5\103\1\132\1\53\50\103\1\0"+
    "\2\3\1\0\1\3\2\0\4\3\1\154\22\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\1\3\1\155"+
    "\25\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\1\3\1\156\25\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\12\3\1\157\14\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\17\3\1\160\7\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\2\3\1\161"+
    "\24\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\14\3\1\162\12\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\17\3\1\163\7\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\17\3\1\164\7\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\24\3\1\165"+
    "\2\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\17\3\1\166\7\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\14\3\1\167\12\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\5\3\1\170\21\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\11\3\1\171"+
    "\15\3\20\0\1\3\1\0\2\3\1\0\1\3\2\0"+
    "\11\3\1\172\15\3\20\0\1\3\1\0\2\3\1\0"+
    "\1\3\2\0\22\3\1\173\4\3\20\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\0\5\3\1\174\21\3\20\0"+
    "\1\3\1\0\2\3\1\0\1\3\2\0\1\175\26\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\14\3"+
    "\1\176\12\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\13\3\1\177\13\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\23\3\1\200\3\3\20\0\1\3"+
    "\1\0\2\3\1\0\1\3\2\0\6\3\1\201\20\3"+
    "\20\0\1\3\1\0\2\3\1\0\1\3\2\0\14\3"+
    "\1\202\12\3\20\0\1\3\1\0\2\3\1\0\1\3"+
    "\2\0\2\3\1\203\24\3\20\0\1\3\1\0\2\3"+
    "\1\0\1\3\2\0\27\3\1\204\17\0\1\3\25\0"+
    "\1\205\47\0\1\206\61\0\1\207\73\0\1\210\32\0"+
    "\1\211\77\0\1\212\33\0\1\213\71\0\1\214\54\0"+
    "\1\215\50\0\1\216\66\0\1\217\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4888];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\22\1\6\11\1\1\11\11"+
    "\1\0\1\1\1\0\26\1\1\11\101\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // Return new symbol objects with line and column numbers in the symbol 
  // left and right fields. This abuses the original idea of having left 
  // and right be character positions, but is   // is more useful and 
  // follows an example in the JFlex documentation.
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  // Return a readable representation of symbol s (aka token)
  public String symbolToString(Symbol s) {
    String rep;
    switch (s.sym) {
      case sym.BECOMES: return "BECOMES";
      case sym.SEMICOLON: return "SEMICOLON";
      case sym.PLUS: return "PLUS";
      case sym.IF: return "IF";
      case sym.STRING: return "STRING";
      case sym.ELSE: return "ELSE";
      case sym.WHILE: return "WHILE";
      case sym.STATIC: return "STATIC";
      case sym.CLASS: return "CLASS";
      case sym.VOID: return "VOID";
      case sym.MAIN: return "MAIN";
      case sym.LPAREN: return "LPAREN";
      case sym.RPAREN: return "RPAREN";
      case sym.APOPPER: return "APOPPER";
      case sym.CPOPPER: return "CPOPPER";
      case sym.AKEY: return "AKEY";
      case sym.CKEY: return "CKEY";
      case sym.DISPLAY: return "DISPLAY";
      case sym.PRINTLN: return "PRINTLN";
      case sym.MINUS: return "MINUS";
      case sym.MULT: return "MULT";
      case sym.AND: return "AND";
      case sym.PUBLIC: return "PUBLIC";
      case sym.MINOR: return "MINOR";
      case sym.LENGTH: return "LENGTH";
      case sym.POINT: return "POINT";
      case sym.TRUE: return "TRUE";
      case sym.FALSE: return "FALSE";
      case sym.THIS: return "THIS";
      case sym.NEW: return "NEW";
      case sym.INT: return "INT";
      case sym.NOT: return "NOT";
      case sym.COMMA: return "COMMA";
      case sym.EXTENDS: return "EXTENDS";
      case sym.RETURN: return "RETURN";
      case sym.IDENTIFIER: return "ID(" + (String)s.value + ")";
      //case sym.NUMBERS: return "NUMBERS(" + (String)s.value + ")";
      case sym.NUMBERS: return "NUMBERS(" + String.valueOf(s.value) + ")";
      case sym.EOF: return "<EOF>";
      case sym.error: return "<ERROR>";
      default: return "<UNEXPECTED TOKEN " + s.toString() + ">";
    }
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { /* ignore whitespace */
          }
        case 42: break;
        case 30: 
          { return symbol(sym.CLASS);
          }
        case 43: break;
        case 3: 
          { return symbol(sym.NUMBERS, Integer.valueOf(yytext()));
          }
        case 44: break;
        case 13: 
          { return symbol(sym.RPAREN);
          }
        case 45: break;
        case 38: 
          { return symbol(sym.DISPLAY);
          }
        case 46: break;
        case 35: 
          { return symbol(sym.LENGTH);
          }
        case 47: break;
        case 23: 
          { return symbol(sym.INT);
          }
        case 48: break;
        case 11: 
          { return symbol(sym.NOT);
          }
        case 49: break;
        case 22: 
          { return symbol(sym.AND);
          }
        case 50: break;
        case 5: 
          { return symbol(sym.POINT);
          }
        case 51: break;
        case 36: 
          { return symbol(sym.RETURN);
          }
        case 52: break;
        case 6: 
          { return symbol(sym.PLUS);
          }
        case 53: break;
        case 40: 
          { return symbol(sym.EXTENDS);
          }
        case 54: break;
        case 9: 
          { return symbol(sym.MINOR);
          }
        case 55: break;
        case 26: 
          { return symbol(sym.TRUE);
          }
        case 56: break;
        case 7: 
          { return symbol(sym.BECOMES);
          }
        case 57: break;
        case 41: 
          { return symbol(sym.PRINTLN);
          }
        case 58: break;
        case 29: 
          { return  symbol(sym.ELSE);
          }
        case 59: break;
        case 28: 
          { return symbol(sym.VOID);
          }
        case 60: break;
        case 2: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 61: break;
        case 27: 
          { return symbol(sym.MAIN);
          }
        case 62: break;
        case 33: 
          { return symbol(sym.STATIC);
          }
        case 63: break;
        case 19: 
          { return symbol(sym.CPOPPER);
          }
        case 64: break;
        case 10: 
          { return symbol(sym.MULT);
          }
        case 65: break;
        case 31: 
          { return symbol(sym.WHILE);
          }
        case 66: break;
        case 21: 
          { return symbol(sym.IF);
          }
        case 67: break;
        case 12: 
          { return symbol(sym.LPAREN);
          }
        case 68: break;
        case 25: 
          { return symbol(sym.THIS);
          }
        case 69: break;
        case 16: 
          { return symbol(sym.AKEY);
          }
        case 70: break;
        case 1: 
          { System.err.println(
	"\nunexpected character in input: '" + yytext() + "' at line " +
	(yyline+1) + " column " + (yycolumn+1));
          }
        case 71: break;
        case 17: 
          { return symbol(sym.CKEY);
          }
        case 72: break;
        case 14: 
          { return symbol(sym.SEMICOLON);
          }
        case 73: break;
        case 20: 
          { /* ignore comment */
          }
        case 74: break;
        case 18: 
          { return symbol(sym.APOPPER);
          }
        case 75: break;
        case 8: 
          { return symbol(sym.MINUS);
          }
        case 76: break;
        case 24: 
          { return symbol(sym.NEW);
          }
        case 77: break;
        case 39: 
          { return symbol(sym.BOOLEAN);
          }
        case 78: break;
        case 37: 
          { return symbol(sym.STRING);
          }
        case 79: break;
        case 15: 
          { return symbol(sym.COMMA);
          }
        case 80: break;
        case 32: 
          { return symbol(sym.FALSE);
          }
        case 81: break;
        case 34: 
          { return symbol(sym.PUBLIC);
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
